package com.arman.investmentandroid

/** Translate display labels without changing persisted portfolio keys. */
object UiText {
    private val fa = mapOf(
        "Investment Android" to "سرمایه‌گذاری اندروید",
        "View Windows Core Snapshot (Read-only)" to "پیش‌نمایش فقط‌خواندنی دادهٔ ویندوز",
        "Windows Core Preview (Read-only)" to "پیش‌نمایش فقط‌خواندنی ویندوز",
        "Inspecting Windows Core snapshot" to "در حال بررسی نسخهٔ ویندوز",
        "Cloud file changed while preparing the backup. Nothing was overwritten; sync again." to
            "فایل ابری هنگام آماده‌سازی پشتیبان تغییر کرد. هیچ داده‌ای جایگزین نشد؛ دوباره همگام‌سازی کنید.",
        "Portfolio holdings match, but Android history differs. No data was overwritten. Choose which history to reconcile." to
            "دارایی‌های گوشی و ابر یکسان‌اند، اما تاریخچه متفاوت است. هیچ داده‌ای جایگزین نشد؛ روش رفع تعارض را انتخاب کنید.",
        "Portfolio holdings match, but Android history differs. Use Cloud Sync to resolve it; no data was overwritten." to
            "دارایی‌های گوشی و ابر یکسان‌اند، ولی تاریخچه فرق دارد. برای رفع تعارض به همگام‌سازی ابری بروید؛ داده‌ای جایگزین نشد.",
        "Windows Core SQLite backups cannot be imported as Android JSON. Nothing was changed." to
            "پشتیبان SQLite ویندوز را نمی‌توان به‌عنوان JSON اندروید وارد کرد؛ داده‌ها تغییر نکردند.",
        "A Windows Core ledger cannot be reduced to Android holdings. Nothing was changed." to
            "دفتر کل ویندوز را نمی‌توان بدون اتلاف اطلاعات به دارایی‌های اندروید تبدیل کرد؛ داده‌ها تغییر نکردند.",
        "History conflict: phone and cloud have different records for the same id. Nothing was overwritten." to
            "تداخل تاریخچه: رکوردهای هم‌شناسه در گوشی و ابر متفاوت‌اند؛ هیچ داده‌ای جایگزین نشد.",
        "History conflict: phone and cloud have different records for the same timestamp. Nothing was overwritten." to
            "تداخل تاریخچه: رکوردهای هم‌زمان در گوشی و ابر متفاوت‌اند؛ هیچ داده‌ای جایگزین نشد.",
        "Cash holdings with quantity other than 1 cannot be imported without changing value. Nothing was changed." to
            "مقدار دارایی نقدی باید یک باشد؛ برای جلوگیری از تغییر ارزش، واردکردن متوقف شد.",
        "All prices updated." to "همهٔ قیمت‌ها به‌روز شدند.",
        "Export Backup" to "خروجی پشتیبان",
        "Import Backup" to "ورود فایل پشتیبان",
        "Restore Previous Local Data" to "بازیابی دادهٔ محلی قبلی",
        "Cloud Recovery Failed" to "بازیابی ابری ناموفق بود",
        "Cloud Sync Failed" to "همگام‌سازی ابری ناموفق بود",
        "Cloud Load Failed" to "بارگذاری ابری ناموفق بود",
        "Cloud Status Failed" to "بررسی وضعیت ابر ناموفق بود",
        "Cloud Setup Failed" to "ایجاد پشتیبان ابری ناموفق بود",
        "Cloud Connection Failed" to "اتصال ابری ناموفق بود",
        "Checking cloud" to "در حال بررسی ابر",
        "Checking cloud status" to "در حال بررسی وضعیت ابر",
        "Syncing safely" to "در حال همگام‌سازی ایمن",
        "Loading cloud data" to "در حال بارگذاری دادهٔ ابری",
        "Exporting backup" to "در حال ذخیرهٔ پشتیبان",
        "Validating backup" to "در حال بررسی پشتیبان",
        "Creating cloud backup" to "در حال ساخت پشتیبان ابری",
        "Validating cloud backup" to "در حال بررسی پشتیبان ابری",
        "If the Google Drive file was moved, removed, or access expired, reconnect it." to "اگر فایل گوگل درایو منتقل یا حذف شده یا دسترسی آن پایان یافته است، دوباره متصل شوید.",
        "Phone and Cloud match." to "دادهٔ گوشی و ابر یکسان‌اند.",
        "First sync needs a choice." to "برای اولین همگام‌سازی باید یکی از نسخه‌ها را انتخاب کنید.",
        "Cloud has newer/different portfolio data." to "دادهٔ ابر نسبت به گوشی تغییر کرده است.",
        "Phone has changes waiting to upload." to "تغییرات گوشی در انتظار بارگذاری هستند.",
        "Conflict: both Phone and Cloud changed." to "تداخل: داده‌های گوشی و ابر هر دو تغییر کرده‌اند.",
        "Phone: " to "گوشی: ",
        "Cloud: " to "ابر: ",
        "Changed asset rows: " to "ردیف‌های دارایی تغییرکرده: ",
        " asset row(s) differ. Nothing was overwritten." to " ردیف دارایی متفاوت است؛ هیچ داده‌ای جایگزین نشد.",
        " asset row(s) differ. Nothing was overwritten. " to " ردیف دارایی متفاوت است؛ هیچ داده‌ای جایگزین نشد. ",
        "Choose which portfolio to keep." to "انتخاب کنید کدام نسخه از سبد نگه داشته شود.",
        "Nothing will be overwritten until you choose." to "تا پیش از انتخاب شما هیچ داده‌ای جایگزین نمی‌شود.",
        "Could not update market prices." to "به‌روزرسانی قیمت‌های بازار ناموفق بود.",
        "Could not restore previous local data." to "بازیابی دادهٔ محلی قبلی ناموفق بود.",
        "Could not process the backup file." to "پردازش فایل پشتیبان ناموفق بود.",
        "Could not process the backup file. Local data was not changed." to "پردازش فایل پشتیبان ناموفق بود؛ داده‌های محلی تغییر نکردند.",
        "Could not write the backup file." to "نوشتن فایل پشتیبان ناموفق بود.",
        "Could not read the backup file." to "خواندن فایل پشتیبان ناموفق بود.",
        "Could not apply the backup file." to "اعمال فایل پشتیبان ناموفق بود.",
        "Could not create the cloud backup file." to "ساخت فایل پشتیبان ابری ناموفق بود.",
        "Could not validate the selected cloud file." to "تأیید اعتبار فایل ابری انتخاب‌شده ناموفق بود.",
        "Could not check the cloud file." to "بررسی فایل ابری ناموفق بود.",
        "Cloud provider did not confirm the complete backup. The previous valid copy is available for recovery." to "ارائه‌دهندهٔ فایل، ذخیرهٔ کامل پشتیبان را تأیید نکرد. نسخهٔ سالم قبلی برای بازیابی در دسترس است.",
        "Phone data changed while sync was running. Nothing was overwritten; run sync again." to "دادهٔ گوشی هنگام همگام‌سازی تغییر کرد. هیچ داده‌ای جایگزین نشد؛ دوباره همگام‌سازی کنید.",
        "Phone data changed while the file was being read. Nothing was overwritten." to "دادهٔ گوشی هنگام خواندن فایل تغییر کرد؛ هیچ داده‌ای جایگزین نشد.",
        "Connected cloud file is not a shared portfolio." to "فایل ابری متصل‌شده، سبد مشترک معتبر نیست.",
        "Connected file is not a shared portfolio." to "فایل متصل‌شده، سبد مشترک معتبر نیست.",
        "Shared portfolio data is missing." to "اطلاعات سبد مشترک وجود ندارد.",
        "Cloud file is not a shared portfolio. No data was overwritten." to "فایل ابری، سبد مشترک معتبر نیست؛ هیچ داده‌ای جایگزین نشد.",
        "Cloud sync requires an investment.shared.portfolio file." to "برای همگام‌سازی ابری به فایل investment.shared.portfolio نیاز است.",
        "Delete " to "حذف ",
        "Set " to "ثبت ",
        "Recover" to "بازیابی",
        "Recommended: use the same Investment-shared.json file as Windows.\n\n" to
            "پیشنهاد: همان فایل Investment-shared.json برنامهٔ ویندوز را انتخاب کنید.\n\n",
        "The file is valid and connected. Load its data now or keep this phone's data? " to
            "فایل معتبر و متصل است. دادهٔ آن بارگذاری شود یا دادهٔ گوشی حفظ شود؟ ",
        "This transaction is not the latest managed change for the asset, " to
            "این تراکنش آخرین تغییر مدیریت‌شدهٔ دارایی نیست، ",
        "This will apply the shared portfolio from Cloud. Android history and settings " to
            "سبد مشترک ابر اعمال می‌شود. تاریخچه و تنظیمات اندروید ",
        "This will reverse the portfolio effect of this transaction " to
            "اثر این تراکنش بر سبد بازگردانده می‌شود ",
        "Both copies may contain changes. " to "هر دو نسخه ممکن است تغییر کرده باشند. ",
        "Smart sync found changes on both Phone and Cloud. " to
            "همگام‌سازی هوشمند در گوشی و ابر تغییر پیدا کرد. ",
        "Smart sync set to every " to "فاصلهٔ همگام‌سازی هوشمند: هر ",
        "Open Portfolio" to "ورود به سبد",
        "My Portfolio" to "سبد سرمایه‌گذاری من",
        "Total Portfolio Value" to "ارزش کل سبد",
        "Tolerance: ±%.1f%%" to "تلرانس: ±%.1f٪",
        "Connect" to "اتصال",
        "Prices updated: " to "آخرین به‌روزرسانی قیمت: ",
        "Prices have not been updated yet." to "قیمت‌ها هنوز به‌روز نشده‌اند.",
        "Portfolio Health: Fix targets (total %.1f%%)" to "وضعیت سبد: مجموع هدف‌ها %.1f٪ است",
        "Portfolio Health: On target" to "وضعیت سبد: مطابق هدف",
        "Portfolio Health: " to "وضعیت سبد: ",
        " asset(s) need attention" to " دارایی نیازمند بررسی است",
        " Summary" to "؛ خلاصه",
        "Buy: " to "خرید: ",
        "  •  Sell: " to "  •  فروش: ",
        "\nRealized P/L: " to "\nسود/زیان تحقق‌یافته: ",
        "\nIncome: " to "\nدرآمد: ",
        "  •  Expense: " to "  •  هزینه: ",
        "Portfolio: %.1f%%  •  Target pool: %.1f%%  •  Target: %.1f%%" to "سهم سبد: %.1f٪  •  سهم هدف‌دار: %.1f٪  •  هدف: %.1f٪",
        "Portfolio: %.1f%%  •  Target: Excluded" to "سهم سبد: %.1f٪  •  خارج از هدف",
        "Distance to target: %+.1f%%" to "فاصله تا هدف: %+.1f٪",
        "Distance to target: Not applicable" to "فاصله تا هدف: ندارد",
        "Invested: " to "سرمایه‌گذاری: ",
        "Value: " to "ارزش: ",
        "Price: " to "قیمت: ",
        "Quantity: " to "مقدار: ",
        "Avg. cost: " to "میانگین خرید: ",
        "P/L: " to "سود/زیان: ",
        "Unrealized P/L: " to "سود/زیان تحقق‌نیافته: ",
        "Since previous snapshot: " to "تغییر از ثبت قبلی: ",
        "Category Breakdown" to "تفکیک دسته‌ها",
        "Holdings" to "دارایی‌ها",
        "Quick Actions" to "عملیات سریع",
        "+ Add Asset" to "+ افزودن دارایی",
        "Price Center" to "مرکز قیمت",
        "Edit Targets" to "ویرایش هدف‌ها",
        "Activity" to "فعالیت‌ها",
        "More Tools" to "ابزارهای بیشتر",
        "Portfolio History" to "تاریخچهٔ سبد",
        "Manage Categories" to "مدیریت دسته‌ها",
        "Undo" to "بازگردانی",
        "Redo" to "انجام دوباره",
        "Settings" to "تنظیمات",
        "Backup / Restore" to "پشتیبان‌گیری / بازیابی",
        "Reset Portfolio" to "پاک‌کردن سبد",
        "Back" to "بازگشت",
        "Back to Portfolio" to "بازگشت به سبد",
        "Cloud Sync" to "همگام‌سازی ابری",
        "Not connected" to "متصل نیست",
        "Connected • first sync pending" to "متصل است • نخستین همگام‌سازی در انتظار",
        "Last known synced" to "آخرین وضعیت همگام است",
        "Local changes pending sync" to "تغییرهای گوشی در انتظار همگام‌سازی",
        "Connected" to "متصل است",
        " • Smart sync " to " • همگام‌سازی هوشمند هر ",
        "m" to " دقیقه",
        " • Smart sync off" to " • همگام‌سازی هوشمند خاموش",
        "Cloud file connected." to "فایل ابری متصل است.",
        "\nSmart sync: " to "\nهمگام‌سازی هوشمند: ",
        "On • every " to "روشن • هر ",
        " min while app is open" to " دقیقه هنگام باز بودن برنامه",
        "\nLast sync: " to "\nآخرین همگام‌سازی: ",
        "Cloud is not connected yet." to "هنوز فایل ابری متصل نشده است.",
        "\nChoose the existing Investment-shared.json from Google Drive," to "\nفایل Investment-shared.json را از گوگل درایو انتخاب کنید،",
        " or create it there if this is your first device." to " یا اگر اولین دستگاه است، آن را بسازید.",
        "Rebalance Summary" to "پیشنهاد متعادل‌سازی",
        "Rebalance: Excluded from target" to "متعادل‌سازی: خارج از هدف",
        "Rebalance: No target set" to "متعادل‌سازی: هدف تعیین نشده",
        "Rebalance: On target" to "متعادل‌سازی: مطابق هدف",
        "Rebalance: Buy about " to "متعادل‌سازی: خرید حدود ",
        "Rebalance: Sell about " to "متعادل‌سازی: فروش حدود ",
        "Recent Activity" to "فعالیت‌های اخیر",
        "Update Nobitex Prices" to "به‌روزرسانی قیمت‌های نوبیتکس",
        "Save All Prices" to "ذخیرهٔ همهٔ قیمت‌ها",
        "Include in target allocation" to "در هدف سبد لحاظ شود",
        "No activity yet." to "هنوز فعالیتی ثبت نشده است.",
        "A price, backup, or cloud operation is already running." to "عملیات قیمت، پشتیبان‌گیری یا ابر هنوز در حال اجراست.",
        "Another backup or sync operation is still running." to "یک عملیات پشتیبان‌گیری یا همگام‌سازی هنوز در حال اجراست.",
        "App lock enabled." to "قفل برنامه فعال شد.",
        "App lock removed." to "قفل برنامه برداشته شد.",
        "Backup exported safely." to "فایل پشتیبان ذخیره شد.",
        "Backup restored safely." to "فایل پشتیبان بازیابی شد.",
        "Change restored." to "تغییر دوباره اعمال شد.",
        "Change undone." to "تغییر بازگردانده شد.",
        "Cloud backup connected and saved." to "پشتیبان ابری متصل و ذخیره شد.",
        "Cloud backup disconnected." to "اتصال فایل ابری قطع شد.",
        "Cloud backup loaded safely." to "پشتیبان ابری بارگذاری شد.",
        "Cloud backup updated safely." to "پشتیبان ابری به‌روز شد.",
        "No assets are included in target allocation." to "هیچ دارایی در هدف سبد لحاظ نشده است.",
        "No cloud file selected. Cloud remains disconnected." to "فایل ابری انتخاب نشد؛ اتصال برقرار نیست.",
        "No file was returned by Android." to "اندروید فایلی برنگرداند.",
        "Nothing to redo." to "تغییری برای انجام دوباره وجود ندارد.",
        "Nothing to undo." to "تغییری برای بازگردانی وجود ندارد.",
        "Phone and Cloud already match." to "دادهٔ گوشی و ابر یکسان‌اند.",
        "Previous local data restored." to "دادهٔ محلی قبلی بازیابی شد.",
        "Transaction reverted." to "تراکنش بازگردانده شد.",
        "Updating Nobitex prices..." to "در حال دریافت قیمت‌های نوبیتکس...",
        "Category already exists" to "این دسته وجود دارد",
        "Enter 0 to 100" to "عددی بین ۰ تا ۱۰۰ وارد کنید",
        "Enter a Nobitex market symbol" to "نماد بازار نوبیتکس را وارد کنید",
        "Enter a category name" to "نام دسته را وارد کنید",
        "Enter a quantity greater than zero" to "مقداری بزرگ‌تر از صفر وارد کنید",
        "Enter a valid average cost" to "میانگین خرید معتبر وارد کنید",
        "Enter a valid balance" to "موجودی معتبر وارد کنید",
        "Enter a valid current price" to "قیمت فعلی معتبر وارد کنید",
        "Enter a valid price" to "قیمت معتبر وارد کنید",
        "Enter a valid transaction price" to "قیمت معاملهٔ معتبر وارد کنید",
        "Enter a value from 0 to 20" to "عددی بین ۰ تا ۲۰ وارد کنید",
        "Enter an asset name" to "نام دارایی را وارد کنید",
        "Incorrect PIN" to "رمز نادرست است",
        "Nobitex source is currently for Crypto assets" to "منبع نوبیتکس فعلاً برای رمزارزهاست",
        "PIN must contain 4–8 digits" to "رمز باید ۴ تا ۸ رقم داشته باشد",
        "PINs do not match" to "رمزها یکسان نیستند",
        "Target must be between 0 and 100" to "هدف باید بین ۰ تا ۱۰۰ باشد",
        "You only own " to "موجودی شما فقط ",
        "No buy or sell transactions yet." to "هنوز خرید یا فروشی ثبت نشده است.",
        "No assets yet. Tap Add Asset to create your first one." to "هنوز دارایی ندارید. برای شروع، دارایی اضافه کنید.",
        "No portfolio snapshots yet. Save prices in Price Center to create one." to "هنوز سابقه‌ای ثبت نشده است. قیمت‌ها را در مرکز قیمت ذخیره کنید.",
        "Portfolio is within tolerance. No rebalance action is needed." to "سبد در محدودهٔ مجاز است؛ نیازی به متعادل‌سازی نیست.",
        "Set targets to a total of 100% to activate rebalance guidance." to "برای فعال‌شدن پیشنهادها، مجموع هدف‌ها را به ۱۰۰٪ برسانید.",
        "Tap name to edit • Long press card to delete" to "برای ویرایش روی نام و برای حذف روی کارت نگه دارید",
        "Update all current prices in one place." to "همهٔ قیمت‌های فعلی را یک‌جا به‌روز کنید.",
        "App Locked" to "برنامه قفل است",
        "Buy" to "خرید", "Sell" to "فروش",
        "Set Final Balance" to "ثبت موجودی نهایی",
        "Activity Manager" to "مدیریت فعالیت‌ها",
        "BUY" to "خرید", "SELL" to "فروش",
        "INCOME" to "درآمد", "EXPENSE" to "هزینه",
        "\nAmount: " to "\nمبلغ: ",
        "\nQuantity: " to "\nمقدار: ",
        "\nPrice: " to "\nقیمت: ",
        "\nRealized P/L: " to "\nسود/زیان تحقق‌یافته: ",
        "\nChange: " to "\nتغییر: ",
        "\nLegacy activity: portfolio-safe revert unavailable" to
            "\nفعالیت قدیمی: بازگردانی ایمن سبد در دسترس نیست",
        "Revert Transaction" to "بازگردانی تراکنش",
        "Revert Unavailable" to "بازگردانی در دسترس نیست",
        "Page %d of %d • %d saved transactions" to "صفحهٔ %d از %d • %d تراکنش ذخیره شده",
        "Newer" to "جدیدتر",
        "Older" to "قدیمی‌تر",
        "Cannot Safely Revert" to "بازگردانی ایمن ممکن نیست",
        "Cloud Backup Connected" to "پشتیبان ابری متصل شد",
        "Edit Target Allocation" to "ویرایش تخصیص هدف",
        "File Picker Unavailable" to "انتخاب فایل در دسترس نیست",
        "Recovery Failed" to "بازیابی ناموفق بود",
        "Verify Current PIN" to "تأیید رمز فعلی",
        "Categories" to "دسته‌ها",
        "Add Category" to "افزودن دسته",
        "Rename Category" to "تغییر نام دسته",
        "Add Asset" to "افزودن دارایی",
        "Edit Asset" to "ویرایش دارایی",
        "App Lock" to "قفل برنامه",
        "Change PIN" to "تغییر رمز",
        "Remove App Lock" to "برداشتن قفل برنامه",
        "Rename" to "تغییر نام",
        "Backup Error" to "خطای پشتیبان‌گیری",
        "Cloud Status" to "وضعیت ابر",
        "Cloud Sync Conflict" to "تداخل همگام‌سازی ابری",
        "Connect Google Drive" to "اتصال به گوگل درایو",
        "Google Drive / Cloud Backup" to "گوگل درایو / پشتیبان ابری",
        "Load from Cloud?" to "دادهٔ ابری بارگذاری شود؟",
        "Nobitex Update" to "به‌روزرسانی نوبیتکس",
        "Nobitex Update Failed" to "به‌روزرسانی نوبیتکس ناموفق بود",
        "Portfolio Tools" to "ابزارهای سبد",
        "Rebalance Tolerance" to "تلرانس متعادل‌سازی",
        "Reset portfolio?" to "سبد پاک شود؟",
        "Restore Previous Local Data?" to "دادهٔ محلی قبلی بازیابی شود؟",
        "Revert transaction?" to "تراکنش بازگردانده شود؟",
        "Smart Sync Interval" to "فاصلهٔ همگام‌سازی هوشمند",
        "Unlock Investment" to "بازکردن برنامه",
        "Prices Not Applied" to "قیمت‌ها اعمال نشدند",
        "Recover Previous Cloud File" to "بازیابی فایل ابری قبلی",
        "Recover only if the connected cloud file is damaged. A valid cloud file will not be replaced." to "فقط برای فایل ابری آسیب‌دیده بازیابی کنید. فایل سالم جایگزین نمی‌شود.",
        "Previous cloud file recovered." to "فایل ابری قبلی بازیابی شد.",
        "Check Cloud Status" to "بررسی وضعیت ابر",
        "Sync Now" to "همگام‌سازی اکنون",
        "Load from Cloud" to "بارگذاری از ابر",
        "Turn Smart Sync Off" to "خاموش‌کردن همگام‌سازی هوشمند",
        "Turn Smart Sync On" to "روشن‌کردن همگام‌سازی هوشمند",
        "Choose Different Cloud File" to "انتخاب فایل ابری دیگر",
        "Disconnect Cloud File" to "قطع اتصال فایل ابری",
        "Quantity" to "مقدار",
        "Current price (Toman)" to "قیمت فعلی (تومان)",
        "Market symbol (e.g. BTC, ETH, SOL)" to "نماد بازار (مثلاً BTC، ETH، SOL)",
        "Target %" to "درصد هدف",
        "Tolerance (%)" to "تلرانس (٪)",
        "4–8 digit PIN" to "رمز ۴ تا ۸ رقمی",
        "Confirm PIN" to "تکرار رمز",
        "Asset name" to "نام دارایی",
        "Category name" to "نام دسته",
        "Current price per unit (Toman)" to "قیمت فعلی هر واحد (تومان)",
        "Average cost per unit (Toman)" to "میانگین خرید هر واحد (تومان)",
        "Final balance (Toman)" to "موجودی نهایی (تومان)",
        "Target allocation (%)" to "تخصیص هدف (٪)",
        "Transaction price per unit (Toman)" to "قیمت هر واحد معامله (تومان)",
        "Cancel" to "انصراف", "Save" to "ذخیره", "Add" to "افزودن",
        "Close" to "بستن", "Continue" to "ادامه", "Delete" to "حذف",
        "Later" to "بعداً", "Load" to "بارگذاری", "OK" to "تأیید",
        "Reconnect" to "اتصال دوباره", "Reset" to "پاک‌کردن",
        "Choose Existing File" to "انتخاب فایل موجود",
        "Create New" to "ساخت فایل جدید",
        "Keep Phone Data" to "نگه‌داشتن دادهٔ گوشی",
        "Load Cloud Data" to "بارگذاری دادهٔ ابری",
        "Restore" to "بازیابی", "Revert" to "بازگردانی",
        "Unlock" to "بازکردن", "Sync Now" to "همگام‌سازی اکنون",
        "Use Cloud" to "استفاده از ابر", "Use Phone" to "استفاده از گوشی",
        "Display unit" to "واحد نمایش",
        "Summary period" to "دورهٔ خلاصه",
        "Automatic Nobitex refresh while app is open" to "به‌روزرسانی خودکار نوبیتکس هنگام باز بودن برنامه",
        "App lock is enabled." to "قفل برنامه فعال است.",
        "Enter your app PIN." to "رمز برنامه را وارد کنید.",
        "Assets within this distance from target are treated as on target." to "دارایی‌های داخل این فاصله از هدف، متعادل محسوب می‌شوند.",
        "Targets must add up to 100%." to "مجموع هدف‌ها باید ۱۰۰٪ باشد.",
        "The app will infer the difference as income or expense." to "اختلاف موجودی به‌صورت درآمد یا هزینه ثبت می‌شود.",
        "The portfolio changed while prices were downloading. Try again; no newer edits were overwritten." to "سبد هنگام دریافت قیمت تغییر کرد. دوباره تلاش کنید؛ تغییرهای جدید شما حفظ شدند.",
        "No Crypto assets are configured with Nobitex as their price source." to "هیچ رمزارزی با منبع قیمت نوبیتکس تنظیم نشده است.",
        "This will delete all assets and transaction history. You can undo it afterward." to "همهٔ دارایی‌ها و تاریخچهٔ تراکنش پاک می‌شوند. پس از آن می‌توانید بازگردانی کنید.",
        "This removes the asset from your portfolio. You can undo it afterward." to "این دارایی از سبد حذف می‌شود. پس از آن می‌توانید بازگردانی کنید.",
        "This recovers the local portfolio preserved immediately before the last import or cloud restore." to "سبد محلیِ ذخیره‌شده پیش از آخرین ورود یا بازیابی ابری برگردانده می‌شود.",
        "This is a core category used by portfolio logic. Add a custom category if you need a different label." to "این دسته در منطق سبد استفاده می‌شود. در صورت نیاز یک دستهٔ سفارشی بسازید.",
        "Use a 4–8 digit PIN. The PIN itself is not stored." to "رمز ۴ تا ۸ رقمی انتخاب کنید. خود رمز ذخیره نمی‌شود.",
        "Off" to "خاموش", "Day" to "روز", "Week" to "هفته",
        "Month" to "ماه", "Year" to "سال",
        "Cash" to "نقد", "Gold" to "طلا", "Stocks" to "سهام",
        "Crypto" to "رمزارز", "Fund" to "صندوق", "Other" to "سایر",
        "Manual" to "دستی", "Nobitex" to "نوبیتکس",
        "Toman" to "تومان", "Rial" to "ریال"
    )

    /** Accept Western, Persian and Arabic-Indic digits in user-entered amounts. */
    fun parseUserNumber(raw: String): Double? {
        val normalized = buildString {
            for (character in raw.trim()) {
                when (character) {
                    in '۰'..'۹' -> append('0' + (character - '۰'))
                    in '٠'..'٩' -> append('0' + (character - '٠'))
                    '٫' -> append('.')
                    '٬', ',', ' ', '\u00a0' -> Unit
                    else -> append(character)
                }
            }
        }
        return normalized.toDoubleOrNull()?.takeIf { it.isFinite() }
    }

    fun translate(value: String, language: String): String {
        if (language != "fa") return value
        fa[value]?.let { return it }
        if (value.startsWith("Investment Android • v")) {
            return value.replaceFirst("Investment Android", "سرمایه‌گذاری اندروید")
        }
        if (value.startsWith("Your portfolio, one step closer to mobile.\nv")) {
            return value.replaceFirst(
                "Your portfolio, one step closer to mobile.",
                "سبد سرمایه‌گذاری شما در گوشی"
            )
        }
        return value
    }
}
