package com.arman.investmentandroid

/** Translate display labels without changing persisted portfolio keys. */
object UiText {
    private val fa = mapOf(
        "Investment Android" to "سرمایه‌گذاری اندروید",
        "Open Portfolio" to "ورود به سبد",
        "My Portfolio" to "سبد سرمایه‌گذاری من",
        "Total Portfolio Value" to "ارزش کل سبد",
        "Tolerance: ±%.1f%%" to "تلرانس: ±%.1f٪",
        "Connect" to "اتصال",
        "Prices updated: " to "آخرین به‌روزرسانی قیمت: ",
        "Prices have not been updated yet." to "قیمت‌ها هنوز به‌روز نشده‌اند.",
        "Portfolio Health: Fix targets (total %.1f%%)" to "وضعیت سبد: مجموع هدف‌ها %.1f٪ است",
        "Portfolio Health: On target" to "وضعیت سبد: مطابق هدف",
        "Portfolio Health: " to "وضعیت سبد: ",
        " asset(s) need attention" to " دارایی نیازمند بررسی است",
        " Summary" to "؛ خلاصه",
        "Buy: " to "خرید: ",
        "  •  Sell: " to "  •  فروش: ",
        "\nRealized P/L: " to "\nسود/زیان تحقق‌یافته: ",
        "\nIncome: " to "\nدرآمد: ",
        "  •  Expense: " to "  •  هزینه: ",
        "Portfolio: %.1f%%  •  Target pool: %.1f%%  •  Target: %.1f%%" to "سهم سبد: %.1f٪  •  سهم هدف‌دار: %.1f٪  •  هدف: %.1f٪",
        "Portfolio: %.1f%%  •  Target: Excluded" to "سهم سبد: %.1f٪  •  خارج از هدف",
        "Distance to target: %+.1f%%" to "فاصله تا هدف: %+.1f٪",
        "Distance to target: Not applicable" to "فاصله تا هدف: ندارد",
        "Invested: " to "سرمایه‌گذاری: ",
        "Value: " to "ارزش: ",
        "Price: " to "قیمت: ",
        "Quantity: " to "مقدار: ",
        "Avg. cost: " to "میانگین خرید: ",
        "P/L: " to "سود/زیان: ",
        "Unrealized P/L: " to "سود/زیان تحقق‌نیافته: ",
        "Since previous snapshot: " to "تغییر از ثبت قبلی: ",
        "Category Breakdown" to "تفکیک دسته‌ها",
        "Holdings" to "دارایی‌ها",
        "Quick Actions" to "عملیات سریع",
        "+ Add Asset" to "+ افزودن دارایی",
        "Price Center" to "مرکز قیمت",
        "Edit Targets" to "ویرایش هدف‌ها",
        "Activity" to "فعالیت‌ها",
        "More Tools" to "ابزارهای بیشتر",
        "Portfolio History" to "تاریخچهٔ سبد",
        "Manage Categories" to "مدیریت دسته‌ها",
        "Undo" to "بازگردانی",
        "Redo" to "انجام دوباره",
        "Settings" to "تنظیمات",
        "Backup / Restore" to "پشتیبان‌گیری / بازیابی",
        "Reset Portfolio" to "پاک‌کردن سبد",
        "Back" to "بازگشت",
        "Back to Portfolio" to "بازگشت به سبد",
        "Cloud Sync" to "همگام‌سازی ابری",
        "Not connected" to "متصل نیست",
        "Connected • first sync pending" to "متصل است • نخستین همگام‌سازی در انتظار",
        "Last known synced" to "آخرین وضعیت همگام است",
        "Local changes pending sync" to "تغییرهای گوشی در انتظار همگام‌سازی",
        "Connected" to "متصل است",
        " • Smart sync " to " • همگام‌سازی هوشمند هر ",
        "m" to " دقیقه",
        " • Smart sync off" to " • همگام‌سازی هوشمند خاموش",
        "Cloud file connected." to "فایل ابری متصل است.",
        "\nSmart sync: " to "\nهمگام‌سازی هوشمند: ",
        "On • every " to "روشن • هر ",
        " min while app is open" to " دقیقه هنگام باز بودن برنامه",
        "\nLast sync: " to "\nآخرین همگام‌سازی: ",
        "Cloud is not connected yet." to "هنوز فایل ابری متصل نشده است.",
        "\nChoose the existing Investment-shared.json from Google Drive," to "\nفایل Investment-shared.json را از گوگل درایو انتخاب کنید،",
        " or create it there if this is your first device." to " یا اگر اولین دستگاه است، آن را بسازید.",
        "Rebalance Summary" to "پیشنهاد متعادل‌سازی",
        "Rebalance: Excluded from target" to "متعادل‌سازی: خارج از هدف",
        "Rebalance: No target set" to "متعادل‌سازی: هدف تعیین نشده",
        "Rebalance: On target" to "متعادل‌سازی: مطابق هدف",
        "Rebalance: Buy about " to "متعادل‌سازی: خرید حدود ",
        "Rebalance: Sell about " to "متعادل‌سازی: فروش حدود ",
        "Recent Activity" to "فعالیت‌های اخیر",
        "Update Nobitex Prices" to "به‌روزرسانی قیمت‌های نوبیتکس",
        "Save All Prices" to "ذخیرهٔ همهٔ قیمت‌ها",
        "Include in target allocation" to "در هدف سبد لحاظ شود",
        "No activity yet." to "هنوز فعالیتی ثبت نشده است.",
        "No buy or sell transactions yet." to "هنوز خرید یا فروشی ثبت نشده است.",
        "No assets yet. Tap Add Asset to create your first one." to "هنوز دارایی ندارید. برای شروع، دارایی اضافه کنید.",
        "No portfolio snapshots yet. Save prices in Price Center to create one." to "هنوز سابقه‌ای ثبت نشده است. قیمت‌ها را در مرکز قیمت ذخیره کنید.",
        "Portfolio is within tolerance. No rebalance action is needed." to "سبد در محدودهٔ مجاز است؛ نیازی به متعادل‌سازی نیست.",
        "Set targets to a total of 100% to activate rebalance guidance." to "برای فعال‌شدن پیشنهادها، مجموع هدف‌ها را به ۱۰۰٪ برسانید.",
        "Tap name to edit • Long press card to delete" to "برای ویرایش روی نام و برای حذف روی کارت نگه دارید",
        "Update all current prices in one place." to "همهٔ قیمت‌های فعلی را یک‌جا به‌روز کنید.",
        "App Locked" to "برنامه قفل است",
        "Buy" to "خرید", "Sell" to "فروش",
        "Set Final Balance" to "ثبت موجودی نهایی",
        "Activity Manager" to "مدیریت فعالیت‌ها",
        "Page %d of %d • %d saved transactions" to "صفحهٔ %d از %d • %d تراکنش ذخیره شده",
        "Newer" to "جدیدتر",
        "Older" to "قدیمی‌تر",
        "Cannot Safely Revert" to "بازگردانی ایمن ممکن نیست",
        "Cloud Backup Connected" to "پشتیبان ابری متصل شد",
        "Edit Target Allocation" to "ویرایش تخصیص هدف",
        "File Picker Unavailable" to "انتخاب فایل در دسترس نیست",
        "Recovery Failed" to "بازیابی ناموفق بود",
        "Verify Current PIN" to "تأیید رمز فعلی",
        "Categories" to "دسته‌ها",
        "Add Category" to "افزودن دسته",
        "Rename Category" to "تغییر نام دسته",
        "Add Asset" to "افزودن دارایی",
        "Edit Asset" to "ویرایش دارایی",
        "App Lock" to "قفل برنامه",
        "Backup Error" to "خطای پشتیبان‌گیری",
        "Cloud Status" to "وضعیت ابر",
        "Cloud Sync Conflict" to "تداخل همگام‌سازی ابری",
        "Connect Google Drive" to "اتصال به گوگل درایو",
        "Google Drive / Cloud Backup" to "گوگل درایو / پشتیبان ابری",
        "Load from Cloud?" to "دادهٔ ابری بارگذاری شود؟",
        "Nobitex Update" to "به‌روزرسانی نوبیتکس",
        "Nobitex Update Failed" to "به‌روزرسانی نوبیتکس ناموفق بود",
        "Portfolio Tools" to "ابزارهای سبد",
        "Rebalance Tolerance" to "تلرانس متعادل‌سازی",
        "Reset portfolio?" to "سبد پاک شود؟",
        "Restore Previous Local Data?" to "دادهٔ محلی قبلی بازیابی شود؟",
        "Revert transaction?" to "تراکنش بازگردانده شود؟",
        "Smart Sync Interval" to "فاصلهٔ همگام‌سازی هوشمند",
        "Unlock Investment" to "بازکردن برنامه",
        "Prices Not Applied" to "قیمت‌ها اعمال نشدند",
        "Recover Previous Cloud File" to "بازیابی فایل ابری قبلی",
        "Recover only if the connected cloud file is damaged. A valid cloud file will not be replaced." to "فقط برای فایل ابری آسیب‌دیده بازیابی کنید. فایل سالم جایگزین نمی‌شود.",
        "Previous cloud file recovered." to "فایل ابری قبلی بازیابی شد.",
        "Check Cloud Status" to "بررسی وضعیت ابر",
        "Sync Now" to "همگام‌سازی اکنون",
        "Load from Cloud" to "بارگذاری از ابر",
        "Turn Smart Sync Off" to "خاموش‌کردن همگام‌سازی هوشمند",
        "Turn Smart Sync On" to "روشن‌کردن همگام‌سازی هوشمند",
        "Choose Different Cloud File" to "انتخاب فایل ابری دیگر",
        "Disconnect Cloud File" to "قطع اتصال فایل ابری",
        "Quantity" to "مقدار",
        "Current price (Toman)" to "قیمت فعلی (تومان)",
        "Market symbol (e.g. BTC, ETH, SOL)" to "نماد بازار (مثلاً BTC، ETH، SOL)",
        "Target %" to "درصد هدف",
        "Tolerance (%)" to "تلرانس (٪)",
        "4–8 digit PIN" to "رمز ۴ تا ۸ رقمی",
        "Confirm PIN" to "تکرار رمز",
        "Asset name" to "نام دارایی",
        "Category name" to "نام دسته",
        "Current price per unit (Toman)" to "قیمت فعلی هر واحد (تومان)",
        "Average cost per unit (Toman)" to "میانگین خرید هر واحد (تومان)",
        "Final balance (Toman)" to "موجودی نهایی (تومان)",
        "Target allocation (%)" to "تخصیص هدف (٪)",
        "Transaction price per unit (Toman)" to "قیمت هر واحد معامله (تومان)",
        "Cancel" to "انصراف", "Save" to "ذخیره", "Add" to "افزودن",
        "Close" to "بستن", "Continue" to "ادامه", "Delete" to "حذف",
        "Later" to "بعداً", "Load" to "بارگذاری", "OK" to "تأیید",
        "Reconnect" to "اتصال دوباره", "Reset" to "پاک‌کردن",
        "Choose Existing File" to "انتخاب فایل موجود",
        "Create New" to "ساخت فایل جدید",
        "Keep Phone Data" to "نگه‌داشتن دادهٔ گوشی",
        "Load Cloud Data" to "بارگذاری دادهٔ ابری",
        "Restore" to "بازیابی", "Revert" to "بازگردانی",
        "Unlock" to "بازکردن", "Sync Now" to "همگام‌سازی اکنون",
        "Use Cloud" to "استفاده از ابر", "Use Phone" to "استفاده از گوشی",
        "Display unit" to "واحد نمایش",
        "Summary period" to "دورهٔ خلاصه",
        "Automatic Nobitex refresh while app is open" to "به‌روزرسانی خودکار نوبیتکس هنگام باز بودن برنامه",
        "App lock is enabled." to "قفل برنامه فعال است.",
        "Enter your app PIN." to "رمز برنامه را وارد کنید.",
        "Assets within this distance from target are treated as on target." to "دارایی‌های داخل این فاصله از هدف، متعادل محسوب می‌شوند.",
        "Targets must add up to 100%." to "مجموع هدف‌ها باید ۱۰۰٪ باشد.",
        "The app will infer the difference as income or expense." to "اختلاف موجودی به‌صورت درآمد یا هزینه ثبت می‌شود.",
        "The portfolio changed while prices were downloading. Try again; no newer edits were overwritten." to "سبد هنگام دریافت قیمت تغییر کرد. دوباره تلاش کنید؛ تغییرهای جدید شما حفظ شدند.",
        "No Crypto assets are configured with Nobitex as their price source." to "هیچ رمزارزی با منبع قیمت نوبیتکس تنظیم نشده است.",
        "This will delete all assets and transaction history. You can undo it afterward." to "همهٔ دارایی‌ها و تاریخچهٔ تراکنش پاک می‌شوند. پس از آن می‌توانید بازگردانی کنید.",
        "This removes the asset from your portfolio. You can undo it afterward." to "این دارایی از سبد حذف می‌شود. پس از آن می‌توانید بازگردانی کنید.",
        "This recovers the local portfolio preserved immediately before the last import or cloud restore." to "سبد محلیِ ذخیره‌شده پیش از آخرین ورود یا بازیابی ابری برگردانده می‌شود.",
        "This is a core category used by portfolio logic. Add a custom category if you need a different label." to "این دسته در منطق سبد استفاده می‌شود. در صورت نیاز یک دستهٔ سفارشی بسازید.",
        "Use a 4–8 digit PIN. The PIN itself is not stored." to "رمز ۴ تا ۸ رقمی انتخاب کنید. خود رمز ذخیره نمی‌شود.",
        "Off" to "خاموش", "Day" to "روز", "Week" to "هفته",
        "Month" to "ماه", "Year" to "سال",
        "Cash" to "نقد", "Gold" to "طلا", "Stocks" to "سهام",
        "Crypto" to "رمزارز", "Fund" to "صندوق", "Other" to "سایر",
        "Manual" to "دستی", "Nobitex" to "نوبیتکس",
        "Toman" to "تومان", "Rial" to "ریال"
    )

    fun translate(value: String, language: String): String =
        if (language == "fa") fa[value] ?: value else value
}
